platform :ios, '9.1'
inhibit_all_warnings!
use_frameworks!

target:'Beautiful' do

    pod 'MJExtension', '3.0.11'
    pod 'SDWebImage', '3.8.1'

    pod 'SnapKit' ,'0.21.1'
    pod 'Alamofire', '3.4.1'
    #pod 'Reflect'

end
